---
- name: debian | installing packages
  apt:
    name: apt-mirror
    state: present
  become: true
  delay: 10
  retries: 6
  
  
- name: debian | update apt-mirror with custom script
  get_url:
    url: https://raw.githubusercontent.com/gentoo9ball/apt-mirror/master/apt-mirror
    dest: /usr/bin/apt-mirror
